### ISSUE TITLE
Shrink/Grow cannon body to 3D model body

### ISSUE THREAD

**Issue by DarrenCook** [superpowers/superpowers-core#114]
(Feature request; or request for documentation if this function is already there.)

If the cannon dimensions/offset are too small/wrong my object keeps sinking into the floor; if too large/wrong my object is floating, and acts like there is a force-field around it. That flexibility is great, but 99% of the time we just want the physics to match the physical appearance, and have the cannon body be exactly the dimensions of the model.

(I'm having loads of trouble getting the cannon dimensions to fit - a cycle of add/subtract 0.1 from any of the 6 offsets/dimensions then run the game again and test collisions, over and over... I feel I must be missing something!!)

**Comment by elisee** [comment]
Hi!

Sorry for not answering earlier. I'm not entirely sure I understand this but it looks like you'd like to be able to use a 3D mesh as a collider in Cannon.js?

Closing in favor of https://github.com/superpowers/superpowers-game/issues/31 which already lists various enhancements that could be made to Cannon.js in Superpowers Game.
