### ISSUE TITLE
"Output folder must be empty" when exporting on Ubuntu 12.04

### ISSUE THREAD

**Issue by ycawidro** [superpowers/superpowers-core#116]
Hello,

I am using superpowers-0.19.0-linux-x64 under ubuntu 12.04.
I have followed the first tutorial and wanted to test it on my server.
Everything seems to be fine except the "publish" function, I only get "Output folder must be empty" message although directory has just been created.

Please advise.
Yanik

**Comment by elisee** [comment]
Hi!

Did you try selecting the folder from the outside rather than entering it in the folder selection popup? Or vice versa? My guess is that it could be an idiosyncrasy of the desktop environment you're running...

**Comment by ycawidro** [comment]
Hello,

Thank you for your answer but sorry I did not see your point here.
Using the interface, I cannot select the folder in another way, I just have a Filer pop-up window.
Can I do the export in CLI ? If yes, how so ?

Yanik.

**Comment by elisee** [comment]
Game export can only be done through the UI I'm afraid. Is it possible your desktop environment creates hidden files in new folders and that might trip things up?

You could also try and go spelunking into the launcher's code and disable the empty folder check? If should be in `resources/app/launcher/main.js`. Look for: 

        if (!isFolderEmpty) {
            event.sender.send("export-folder-failed", "Output folder must be empty.");
            return;
        }

And comment out those lines? You could also try adding a `console.log` call that will print out `fs.readdirSync(outputFolder).length` as well as `outputFolder` itself to check what's going on.

**Comment by bilou84** [comment]
This one should be fixed now that we properly ignore every file/folder starting with a ".".
Feel free to reopen if you still encounter problems.
