### ISSUE TITLE
Headless server not connecting

### ISSUE THREAD

**Issue by Vynlar** [superpowers/superpowers-core#117]
### What I've Done
I downloaded the 64-bit linux version of Superpowers, extracted it on my 14.04 Ubuntu server and followed the directions at the bottom of [this page](http://docs.superpowers-html5.com/en/getting-started/setting-up-superpowers). The directions are slightly wrong, as it asks you to use 'cd resources/app' and then run 'node app/server start' which should read 'node server start'. The server turns on successfully. I forwarded ports 4237-8.

### The Problem
* The page successfully loads with the project interface, but at the center of the window it reads "Connecting..."
* The following errors shows up in the Chrome console: [image](http://puu.sh/nnJ6J/f64bb5f50b.jpg),
followed by a failed Socket.io connection every 5 seconds or so.
* Connecting using the desktop client does not work either.

**Comment by elisee** [comment]
Hi!

Thanks for the report, fixed the `node server start` command in https://github.com/superpowers/docs.superpowers-html5.com/commit/ef25006ffad21af05a4a3a20702b8d2924cede1a.

Regarding your problem:

 * Is it possible you have a firewall or reverse proxy on your server that doesn't forward WebSocket connections? You seem to be able to access the static files but the WebSocket connection fails
 * The `locales/undefined` bit seems weird. What language is your browser configured to use/request? Can you try setting it to English to see if maybe there's an issue in the locale fetching mechanism?

**Comment by Vynlar** [comment]
* I do have Nginx running, but I am not using it for the Superpowers server. I started up a different server that uses socket.io and it connected without issue.
* My Windows(7) is already in English as well as chrome.

**Comment by elisee** [comment]
Did you ever manage to get it working? If you still need help, please feel free to re-open.

**Comment by drewmo** [comment]
I am having the same issue. I am starting with a new ubuntu VPS at DigitalOcean, putting the superpowers files in a user directory, running the nodejs server start command, and going to the ipaddres:4237.

I can see the page loading, it requests me to login (since i setup a password) but it just shows connecting... forever.

I get endless attempts to send a request to: "ws://my_digitalocean_ip:4237/socket.io/?EIO=3&transport=websocket with a status code of 101 every 1.5 mins.

All I have done to change the VPS is to install nodejs with apt-get.

**Comment by drewmo** [comment]
@elisee I am still running into this issue. I can't seem to get the server to connect, it will display the page but the serve address is not showing up in the top left, only: "hub:serverAddress"
