### ISSUE TITLE
client: Browser tab doesn't have proper title when opening asset from a link

### ISSUE THREAD

**Issue by bilou84** [superpowers/superpowers-core#121]
It works when opening the asset from the main window with the button.

We should add a `setupWindowTitle` function on SupClient to do the job. It will take the projectClient and the id of the asset as parameters. It must subscribe to the entries through the projectClient to recover the name and update the document's title.

See https://github.com/superpowers/superpowers-core/blob/master/client/src/project/index.ts#L982 and https://github.com/superpowers/superpowers-game/blob/master/plugins/default/sprite/componentEditors/SpriteRendererEditor.ts#L177 + https://github.com/superpowers/superpowers-game/blob/master/plugins/default/sprite/componentEditors/SpriteRendererEditor.ts#L257

**Comment by andapopovici** [comment]
Hi there, I've cloned your project and built it, it looks great so far! I was trying to reproduce your bug and this is a stupid question but how do you open an asset from a link? I've managed to create an asset and click the button to open it in a new tab which does have the correct title as you mention.

I'd love to contribute so this clarification would be great. Thanks :)

**Comment by elisee** [comment]
The title is currently set manually by the main project window when opening an asset.

Here are the steps to reproduce the issue:

 * Access your server through the browser (http://localhost:4237)
 * Open a project, and open an asset in a new tab using the little icon to the right
 * Copy the URL and open it in another tab. It won't have a title. Or simply reloading the tab might work.

Ideally the title of the window should also auto-update when the asset or one of its parent folders are renamed.

**Comment by elisee** [comment]
Fixed in 4200ab449243c15ca8f0e117b7ed86231ac580e0.
