### ISSUE TITLE
While building: npm WARN deprecated graceful-fs@3.0.8

### ISSUE THREAD

**Issue by mk-pmb** [superpowers/superpowers-core#122]
While building 2f266e9a7948c1ff24b97ffd8f251fca785944ab with Node.js v5.7.1, npm v3.6.0 on Ubuntu 12.04.5 LTS precise:

> npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by elisee** [comment]
Various of our dependencies currently rely on `graceful-fs@3` which has been deprecated. Not much we can do about it except update our dependencies from time to time until they all moved to v4+.

I'm sure once `graceful-fs@3` actually stops working, we'll hear about it through various channels.
