### ISSUE TITLE
Server crash if you move a folder

### ISSUE THREAD

**Issue by maxlxl** [superpowers/superpowers-core#124]
I just created a new project. I created one folder named 'documentation' and after that a second folder named 'assets'. The folder 'assets' appeared in the tree under 'documentation'. As I moved the 'asset'-folder in the main tree the server crashed.
Server: Superpowers node 0.19.0 @ Linux Debian 8
Client: Superpowers app 0.19.0 @ Windows 7 Ultimate

**Comment by maxlxl** [comment]
I tested the issue with the newest compiled version and got this error in the server console:
```
TypeError: Cannot read property 'length' of undefined
    at A:\superpowers builder\superpowers\core\server\RemoteProjectClient.js:131:80
    at FSReqWrap.oncomplete (fs.js:82:15)
```
The crash can be recreated by creating on folder and another folder in the first one. After that move the second folder in the main tree and then the server crashes.

**Comment by Tititesouris** [comment]
I just got the same error by doing the same thing.
I also get a
`SyntaxError: Unexpected token u
    at Object.parse (native)
    at C:\...\superpowers-0.19.0-win-x64\resources\app\systems\game\plugins\default\scene\data\SceneAsset.js:40:57
    at FSReqWrap.oncomplete (fs.js:82:15)`
when trying to restart the server

**Comment by maxlxl** [comment]
I can start my server again without any error. Only the created folder was not saved.

**Comment by elisee** [comment]
Sorry for the late reply. I believe this one is fixed in the dev version, but we'll keep it open until after the release just in case.

**Comment by elisee** [comment]
v1.0.0 has been released. Please re-open if you still encounter that bug, but it should be fixed.

**Comment by Jose-Moreno** [comment]
@elisee Hi. I downloaded v 1.1.0 today and I have this same bug. The way I reproduced this is that whenever folders are created inside other folders, nested in their hierarchy I have to move them outside of the hierarchy and the server crashes. I get this error everytime it crashes:

26/8/2016 22:24:32 - The server crashed.
TypeError: Cannot read property 'length' of undefined
    at C:\Users\MORE\AppData\Roaming\Superpowers\core\server\RemoteProjectClient.js:150:80
    at FSReqWrap.oncomplete (fs.js:117:15)

If I create the folders each on the same level, move them inside other folders and then move them outside again the server doesn't crash.

Also everytime the server crashes, if I press the "start" button the "My Server" tab never updates automatically, so I have to close it and reopen it to view my projects again. Plus when the server is running again the Superpowers Project Window shows a reconnect button, but when I press it after the server has been restarted, nothing happens and Only my name appears in the chat to the right, while the left sidebar shows the message "connecting..." forever.

Hope this is thorough enough an explanation. You people are incredible keep up the great work! If you guys need a video showing this issue let me know! :)

**Comment by elisee** [comment]
Thanks for the detailed report. @bilou84 fixed anoter crash this month, the fix will be in v2 (to be released shortly), see https://github.com/superpowers/superpowers-core/commit/f514f7e0abb01a4468b2b4c47c0facf78114401d so I assume this is the same bug.
