### ISSUE TITLE
Checking for updates and installing them

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-core#125]
` server/index.ts` can be invoked in one of two ways: through the command line, or through the app

 * [x] `node server registry`
 * [x] `node server update core` and `node server update core@${version}`
 * [x] `node server update ${systemID}`
 * [x] Check if we're in the dev version (`.git` exists) in core and systems
 * [x] Make sure we download to temporary locations and only delete after everything has been successfully downloaded

##  `node server registry`

This command should fetch the registry and annotate it with what versions of each system or plugin are installed, if any, and for those, also fetch the latest version number. It should also display systems and plugins installed but not found in the registry!

In command-line mode, this should be pretty-printed  
When access from the app, it should send the resulting JSON with `process.send()`.

## `node server update core`

This command should fetch the latest core version and compare with current installed.

In command-line mode, it should offer updating, maybe using [inquirer](https://www.npmjs.com/package/inquirer).
From the app, it should just return the installed and latest version numbers with `process.send()` and exit.

if a version number is passed with `@version`, then the update should happen right away without awaiting confirmation. This will be used by the app.

## `node server update system`

Update a system and all of its installed plugins. As previously established, `common` and `default` plugins are always installed and cannot be removed. (It will be possible to enable/disable `default` plugins per-project later).

In command-line mode, it should offer updating, maybe using [inquirer](https://www.npmjs.com/package/inquirer).
From the app, it should just do the updates right away.

(Later on, we can have a more complex syntax with `node server update system:author/plugin@version`, but it seems overkill for now.)

**Comment by bilou84** [comment]
Instead of the @version to skip confirmation, maybe we should go for a --force flag. There is a confirmation to skip when uninstalling stuff as well. So maybe one common flag would be a better solution?

**Comment by elisee** [comment]
Yup, sounds good!
