### ISSUE TITLE
Can't build from source - missing client/index.js

### ISSUE THREAD

**Issue by beeglebug** [superpowers/superpowers-core#130]
I've tried to pull the repo and build from source so I can start trying to tackle some of the open issues, but after following the build instructions I hit an error when the build script tries to build the client folder, it's expecting an index.js, but it's not there.

The client folder contains an index.d.ts, but not an index.ts, which I presume is the problem, but I have no idea what that file should contain, so I can't really fix the issue myself.

**Comment by elisee** [comment]
Hi!

Looks like `gulp-typescript` had an accidental breaking change a few days ago. I forced the version to the last known good for now: https://github.com/superpowers/superpowers-core/commit/9f902dedaf73dbac851123c58311fcf9e1cd1513

Cheers!
