### ISSUE TITLE
Systematically disconnected when trying to modify a script

### ISSUE THREAD

**Issue by raaaahman** [superpowers/superpowers-core#132]
I'm using Superpowers 0.19.0 for Windows 64-bit (with Windows 7).

In a project I have a few scripts that I'm not able to modify because I'm being disconnected everytime I write a single digit/character in the script (even if it's a space or a line-break). Other script in this project work just right, and my other Superpowers projects are working fine too.

If I duplicate these scripts assets (either with ctrl + D or by copy/pasting in a new script asset), I just run into the same problem (systematically disconnected).

I did a few Git manipulations just before this problem occured, so I believe it's related. (I reset the project to a former stage and deleted an empty branch) I'm not really used to Git (or even versionning) so I believe I just screwed up by myself, but I believe the behavior of those... well, Behaviors was worth pointing out.

**Comment by elisee** [comment]
It might be a line ending issue related to Git? Try opening the script.ts files in your favorite text editor and switching the line endings to CRLF or LF.

**Comment by raaaahman** [comment]
As simple as that. Thank you very much, I wasn't aware of those compatibility issues with text format.

**Comment by elisee** [comment]
Thankfully this will be dealt with automatically in the next version of Superpowers, see https://github.com/superpowers/superpowers-game/commit/134f87d2cc09bc108edd520217592b899a5b234d.
