### ISSUE TITLE
Server management cancel buttons are missing text

### ISSUE THREAD

**Issue by IvanFon** [superpowers/superpowers-core#134]
As shown below: 

![image](http://i.imgur.com/Bu1bLnA.png)

The cancel button says "common:actions:cancel". This happens for the add server, rename, edit address and remove server dialogues.

**Comment by elisee** [comment]
Hi!

Thanks, that's a known issue with the old launcher because it didn't have internationalization support. Fixed in the new app coming soon: https://github.com/superpowers/superpowers-app
