### ISSUE TITLE
Typescript error checking is extremely slow

### ISSUE THREAD

**Issue by Pixelrobin** [superpowers/superpowers-core#136]
I'm using version 0.22.0-dev and I've used both electron 1.1.1 and Google Chrome to try to edit projects. In both cases, (Even though Chrome was better) the script editor got extremely laggy. On Chrome, it seemed to get worse over time over time. In electron, it was slow from the start. Typing a single character would freeze the screen for a good few seconds while it attempts to detect errors. It's even worse when trying to do a multi-line comment, as it becomes almost impossible to close the comment because of the freeze checking the rest of the lines that were unintentionally commented. This makes superpowers almost completely unusable.

I'm on a lower-end laptop, but it should be able to handle a code editor, right?

[Here is a gif](http://imgur.com/6Iynj8G). It's kinda painful to watch :p.
Since it's hard to tell, this is what is going on:

1. I opened the script asset. Notice the long loading time. During this loading time, I attempted to change the cursor position and scroll down.
2. When the scrolling finally worked, I scrolled to the bottom and added 2 new lines.
3. After that, I typed some words at a normal typing speed. They didn't appear until much later.
4. After they did appear, there was yet another delay as the editor attempted to find errors. During this time,  I attempted to change the cursor position a few times and select something.
5. Finally, I commented what I wrote. It froze again and took a while to realize that there were no more errors.

This doesn't happen in the latest stable release (0.19.0). This is probably a critical issue :D.

**Comment by LukeLanFaust** [comment]
I can also confirm this on a low-end laptop as well, 1.4ghz dual core, and 8gb RAM. I'm using 0.19.0, but it only happens with a large amount of code in a script. From what I can tell, it's either the syntax highlighter updating, or something else might be updating the entire page whenever a letter is added.

In 0.19.0 it's very minor though, so it might help to check what changed between versions?

**Comment by Pixelrobin** [comment]
I think it's the syntax highlighter. Here are my specs if it helps:

- Intel Core i7-4700MQ CPU @ 2.40GHz
- 8 GB RAM
- 64 bit OS, x64 processor
- Graphics are built-in

**Comment by fraxken** [comment]
I confirm too. I think the typescript linter make horrible freeze (for all users connected to the project).

**Comment by bilou84** [comment]
Completely missed that one. Seems to be quite important indeed. Will have a look as soon as possible

**Comment by bilou84** [comment]
Ok so with the following commit, the performance should be a lot better.
https://github.com/superpowers/superpowers-game/commit/acefd51fad7a1c81540386c6977bee59fba1f017

Can you check it out and let me know?

**Comment by Pixelrobin** [comment]
I will check it out as soon as I can, will edit result in later!
