### ISSUE TITLE
Attempting to edit script from cloned git repo results in being disconnected from server

### ISSUE THREAD

**Issue by robrtsql** [superpowers/superpowers-core#139]
This problem occurs with Windows 10, 64-bit, using both the Superpowers editor both using the desktop app and from the browser.

Steps to reproduce:
* git clone "discover-superpowers" repo into projects directory
* Start superpowers server and begin editing discover-superpowers project
* Open Player Behavior and attempt to edit script
* Get "You were disconnected." message

The same problem does not occur if I make a new script via Superpowers and attempt to edit it--the problem only occurs with scripts from the repository. It seems like it could be some sort of file permissions issue, but I didn't have any trouble editing the files with any other editors.

**Comment by elisee** [comment]
Are you using the latest release (v0.19) or the development version from GitHub? This bug happens because of line endings differences and it has supposedly been fixed in the development version, see https://github.com/superpowers/superpowers-game/commit/134f87d2cc09bc108edd520217592b899a5b234d

**Comment by robrtsql** [comment]
Oops! I was using v0.19. Building the development version and running that fixed it. Thanks!
