### ISSUE TITLE
Pas de prévisualisation sur serveur externe

### ISSUE THREAD

**Issue by Rouliboudin** [superpowers/superpowers-core#145]
La prévisualisation du projet ne marche pas pour moi lorsque je suis sur le serveur de mon ami.
![2016-07-20_222021](https://cloud.githubusercontent.com/assets/20565757/17002086/1228632a-4eca-11e6-8baf-c9895637cd0d.png)
La fenêtre reste blanche. Il arrive à lancer le jeu sans problème. J'ai redémarré mon ordinateur, relancé Superpowers plusieurs fois mais rien ne change. La prévisualisation de projet marche sur mon serveur local. help

**Comment by anatagawa** [comment]
Y'a de grande chance qu'il n'ai pas ouvert le second port pour le build.

Les deux ports a ouvrir sont par défaut le 4237 pour accéder au Server, et le 4238 pour le build, que les gens puisse lancer la preview du jeu

**Comment by elisee** [comment]
Je pense que la réponse d'Anata est correcte. Je pense pas que c'est un bug du coup je ferme le ticket. Si besoin, tu peux toujours réouvrir.
