### ISSUE TITLE
Possible bug in ArcadeBody2D

### ISSUE THREAD

**Issue by rastating** [superpowers/superpowers-core#154]
Hello,

I'm running into a really weird error, which I think may possibly be a bug in the core code.

I'm detecting when an actor goes a certain distance off screen, and when they do, I want to reset their position to a point on screen. However, when doing this, the actor is only for a brief moment set to the specified position, and after that will continue to descend from the point they previously were; as if the position had never been reset.

I have created a small example, based off the platformer demo, to illustrate the issue. The demo project can be downloaded from: http://static.rastating.com/superpowers/arcade-body-bug.zip

Alternatively, if you'd rather paste the example code into a project yourself - create a new project using the platformer sample, create a gap in the tile map for the character to fall through, and then paste this code into the top of the ```update``` method of the character behavior:

```javascript
    // Log to the console the current Y position of the actor - keep your eye on this when debugging.
    Sup.log(this.actor.getY());
    
    // If we fall below -200, then disable the arcadeBody so we can see from the log above that the Y position
    // does indeed get reset to zero.
    if (this.actor.getY() < -200) {
      this.actor.arcadeBody2D.setEnabled(false);
      this.actor.setPosition(-3.868, 0);
    }
    
    // After verifying the Y position has been reset to zero as per above, click the P key, and you'll see
    // that once  the arcadeBody is re-enabled it will instantly pick up from the same Y position prior
    // to it being reset to zero.
    if (Sup.Input.isKeyDown("P")) {
      this.actor.arcadeBody2D.setEnabled(true);
    }
```

As per the comments in the code, once the character has fallen below -200, it will disable the arcadeBody and set the position back above the platform, at this point, we'll see in the console output that the Y position isn't budging from zero at all. However... should you then press the P key, you'll see it will start reporting that we're descending from the same Y position that we were previously.

Example output from my console:

```
-188.6999969482422
-191.4199981689453
-194.16000366210938
-196.9199981689453
-199.6999969482422
-202.5
0
205.32000732421875
208.16000366210938
211.02000427246094
213.89999389648438
216.8000030517578
219.72000122070312
0
```

As you can see, it doesn't start descending from 0 once P is pressed, it just jumps straight back to 205.

Hopefully this will be enough information, if anymore is needed though please let me know :)

**Comment by StuffBySpencer** [comment]
Answered this over in the game repo: https://github.com/superpowers/superpowers-game/issues/160
