### ISSUE TITLE
Create a thread in html5gamedevs?

### ISSUE THREAD

**Issue by proyb6** [superpowers/superpowers-core#29]
I understand you have a forum, at html5gamedevs, there are largest community members you should be made SuperPowers a presence there and most of us already have user accounts. Hope to see you there!

http://www.html5gamedevs.com/

**Comment by elisee** [comment]
Probably a good idea. Anyone in the community who already has an account there wants to give it a shot?

**Comment by proyb6** [comment]
I think the official admin need to create a section/category for
SuperPowers, I hope the creator could email them.

**Comment by nounoursheureux** [comment]
I think creating a section for Superpowers would be a good idea :+1:
Hope the admins think so

**Comment by elisee** [comment]
Posted in the Welcome thread to introduce myself, Superpowers and ask if a forum for it can be created. My post is awaiting moderation: http://www.html5gamedevs.com/topic/1-welcome/?page=7#comment-112821

**Comment by neuhaus** [comment]
Btw, will superpowers have a presence at FOSDEM?

**Comment by elisee** [comment]
@neuhaus There won't be anobody from @SparklinLabs, we'll be busy taking part in the Global Game Jam! Haven't heard from anyone else in the community going atm.

**Comment by elisee** [comment]
Closing this for now since I won't have time to look more into it. If someone wants to work on getting this done, feel free to reopen.
