### ISSUE TITLE
Zoom In and Out Shortcuts Act Weird on Mac, If cmd Key is Pressed

### ISSUE THREAD

**Issue by ArgosOz** [superpowers/superpowers-core#64]
Mac, Yosemite, 10.10.4

ctrl + plus zooms in and ctrl + minus zooms out.
alt + plus zooms in and alt + minus zooms out.
shift + plus zooms in and shift + minus zooms out.

Just zoom in and out using above methods as much as you like and then use zoom function with cmd key... It zooms one level up once and/or one level down once, later stops zooming as if no keys pressed... then try to zoom in and out using ctrl, alt or shift keys, nothing happens until you pressed + or - twice then it zooms in or out again as expected.

**Comment by elisee** [comment]
Do you happen to know if Cmd+Plus is a browser- or OS-level command that might mess with things?

**Comment by ArgosOz** [comment]
I don't know but I believe it's application level.

**Comment by elisee** [comment]
Closing since there hasn't been any news on this for a long time. See https://github.com/superpowers/superpowers-game/pull/132 and https://github.com/superpowers/superpowers-game/issues/123 for details about very quick zoom bug.
