### ISSUE TITLE
Scene Editor Consumes Too Much Energy on Mac

### ISSUE THREAD

**Issue by ArgosOz** [superpowers/superpowers-core#68]
Mac, Yosemite, 10.10.4

"Energy Impact: A relative measure of the current energy consumption of the app. Lower numbers are better." 

"The Energy tab of Activity Monitor displays the Energy Impact of each open app based on a number of factors including CPU usage, network traffic, disk activity and more. The higher the number, the more impact an app has on battery power."

[Source](https://blog.mozilla.org/nnethercote/2015/08/26/what-does-the-os-x-activity-monitors-energy-impact-actually-measure/ )

...

Scene Editor's "energy impact" value can quickly go over 100 and heat the computer then all the fans fires up to cool down. If you close the Scene Editor tab, everything goes back to normal. I've never seen this before, even hungry apps usually impact around max 30-40 for a very short amount of time. 

Other Superpowers editors have considerably low energy impact on my computer. 

For comparison...

JetBrains' Webstorm example:
* Webstorm window is focused.
* 3 tabs are open.
* The program is IDLE...

Energy impact is around 6-7.

Superpowers example:
* The window is focused.
* 4 tabs are open. 
   * One tab is Scene Editor tab but not the active one.
* The program is IDLE...

Energy impact is around 22-27.

I closed the Scene Editor tab... Energy impact immediately dropped down to 4-6.

There's something wrong with Scene Editor and this is bad because it would drain laptop batteries quickly.

**Comment by elisee** [comment]
Thanks for the report. Have yuo tried the 3D model editor? Doesn't it have a similar impact?

**Comment by ArgosOz** [comment]
I tried 3D model editor now, and yes, it is similar.

**Comment by elisee** [comment]
OK, so my guess is that it's simply the result of those editors being more like games than regular editors. They have a render loop that runs 60 times a second (necessary for animations, etc.). You cannot compare with Webstorm which must only redraw whatever changes.

We might want to throttle the render loop when the tab is hidden though!

**Comment by ArgosOz** [comment]
> We might want to throttle the render loop when the tab is hidden though!

Good idea.

**Comment by DarrenCook** [comment]
I'd also noticed this (on Linux). I agree that throttling (well, putting to sleep) each tab when it is not visible is a good solution.

**Comment by bilou84** [comment]
Done here https://github.com/superpowers/superpowers-game/commit/7a27871a9b3630b08950671714e1e338bba9f401
