### ISSUE TITLE
Allow duplicating asset folders

### ISSUE THREAD

**Issue by bilou84** [superpowers/superpowers-core#77]

**Comment by nounoursheureux** [comment]
I can think of two ways of implementing it, I think the first one is better but I prefer to ask for advice:
- The client could send a single message to the server, with the folder ID and its new name, and the server then duplicates all the assets contained in the folder
- Or the client could send a message to create the new folder, then loop through the assets contained in the folder and duplicate them one by one to the new folder.       

What do you think ?

**Comment by elisee** [comment]
Server-side would be much better.

Currently recursive asset deletion is done on the client-side and it's not great (see https://trello.com/c/lbEsvIBP/411-server-client-move-recursive-entry-deletion-to-server-so-that-it-s-more-robust). I'll create an issue for it too.

**Comment by nounoursheureux** [comment]
I'm working on this issue :ok_hand:

**Comment by nounoursheureux** [comment]
I got it working :+1: . I just need to do some cleanup and then I will send a PR
