### ISSUE TITLE
Deleting an asset with a scheduled save doesn't cancel scheduled save

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-core#90]
It looks like deleting an asset with a scheduled save doesn't cancel the scheduled save, leading to ENOENT error messages in the console.

To reproduce:

 1. Create a sprite
 2. Upload a texture
 3. Within a minute, trash it
 4. Wait 60 seconds

**Comment by chrisbubernak** [comment]
I'll go ahead and take a look at this.
