### ISSUE TITLE
Offbeat preview when selecting frames for a sprite animation

### ISSUE THREAD

**Issue by Komanaki** [superpowers/superpowers-core#92]
Hello everyone,

I think I've got a tiny UI problem on the sprite editor when working with animations, but it doesn't seems to affect the sprite animation system in itself.
It appeared while using a tiled sprite with 6 columns and 4 rows, but I guess you can reproduce it with a different tiled sprite.

**OS :** Windows 10 x64
**Superpowers :** 0.19.0 x64

**How to reproduce :**
1. Create a "Sprite" asset
2. Import a tiled sprite as the "Texture"
3. Set the grid size of the sprite using the "Setup" button
4. Create a new animation
5. Set the first (left) number of the animation as 0 (= the first image of the first row)
6. Increase the second (middle) number of the animation up to 6 (= the first image of the second row)

**Expected behavior :**
The purple preview layer shown over the sprite should highlight the first row (6 images) and the first image of the second row, as they're the selected sprites for the created animation.

**Encountered problem :**
The purple preview layer exeeds the first row on its right and highlights a 7th non-existent image. The animation preview at the bottom of the editor still works and understands that we want the images of the tiled sprite between indexes 0 and 6.

Here is a visual representation of the issue, I've added the sprites index myself for more clarity.
![01-29-2016 14-14-33](https://cloud.githubusercontent.com/assets/1526969/12676469/cd3257fe-c692-11e5-97fd-b1338a36f13d.png)

And here's the sprite configuration for reference.
![01-29-2016 14-15-38](https://cloud.githubusercontent.com/assets/1526969/12676471/d0a07164-c692-11e5-8cd0-5c5c26178c94.png)

It's my first issue report so I hope it's understandable enough. :smile: 
Cheers,

**Comment by bilou84** [comment]
Hello! Thanks for the very clear report :D

For now, the size of texture must be exactly a multiple of your grid size. In your case, it should be 198*228.

We should (and can) make a better work to ignore the pixels that are out of the grid so you don't have that kind of surprises !

Leaving this bug open so we don't forget to fix this at some point!

**Comment by Komanaki** [comment]
Okay, I think I understand well the problem now !

As it's a tiled sprite with 1-pixel separators between each frame, its dimensions aren't peer indeed ^^"
It may explains why the calculated grid size may not be perfect, plus Superpowers doesn't support offsets between sprites frames at the moment.
Despite the rarity of this problem, I hope I'll still be useful !

And thanks for the fast answer too :)

**Comment by bilou84** [comment]
Yeah this is another issue but at some point we definitely should support a offsets between frames!

**Comment by elisee** [comment]
Closing in favor of https://github.com/superpowers/superpowers-game/issues/120 since this is a Superpowers Game issue.
